id: P000644
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:55:41.940597
source_metadata:
  id: bdr:W00KG01621
  title: ཉེ་བརྒྱུད་ཡི་གེ་དྲུག་པའི་སྒོམ་ལུང་འབོགས་ཚུལ
  author: ''
  volumes:
    5e163ddabf3d4662b01678a11f2b715f:
      image_group_id: I00KG02880
      title: ''
      volume_number: 1
      total_pages: 18
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
